name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t joeljeff/main:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag joeljeff/main:latest docker.io/joeljeff/main:latest
          docker push docker.io/joeljeff/main:latest
